import { avCol, inits } from './helpers.jsx';
import { CLIENTS } from './mock-data.jsx';

// ── SIMPLE CS PAGES ───────────────────────────────────────────────────────────
export const SuspendedPage  = () => { const s=CLIENTS.filter(c=>c.status==='suspended'); return (<><div className="ph"><div><div className="ph-title">Suspended Clients</div><div className="ph-sub">{s.length} client{s.length!==1?'s':''} currently suspended</div></div></div><div className="tbl-wrap"><table><thead><tr><th>Client</th><th>Zone</th><th>Funder</th><th>Suspension type</th><th>Status</th></tr></thead><tbody>{s.map(c=><tr key={c.id}><td><div className="client-cell"><div className="cav" style={{background:avCol(c.name),width:30,height:30,fontSize:11}}>{inits(c.name)}</div><div><div className="cname">{c.name}</div><div className="cid">{c.id}</div></div></div></td><td><span className="tag t-navy">{c.zone}</span></td><td style={{fontSize:'12px',color:'var(--slate)'}}>{c.funder}</td><td><span className="tag t-amber">Hospitalisation</span></td><td><span className="tag t-amber">Suspended</span></td></tr>)}</tbody></table></div></>); };
export const DischargedPage = () => (<><div className="ph"><div><div className="ph-title">Discharged</div><div className="ph-sub">Archived client records</div></div></div><div style={{textAlign:'center',padding:'60px 20px',color:'var(--slate)'}}><div style={{fontSize:40,marginBottom:12}}>📁</div><div style={{fontFamily:'var(--fh)',fontSize:'15px',fontWeight:600,color:'var(--navy)',marginBottom:6}}>No discharged clients</div><div style={{fontSize:'12.5px'}}>Discharged clients will appear here</div></div></>);
export const MedicationsPage= () => (<><div className="ph"><div><div className="ph-title">Medications</div><div className="ph-sub">MAR summary across all active clients</div></div></div><div className="kpi-row"><div className="kpi kpi-green"><div className="kpi-label">Admin rate</div><div className="kpi-val">96%</div><div className="kpi-sub">Last 7 days</div></div><div className="kpi kpi-amber"><div className="kpi-label">Refusals</div><div className="kpi-val">3</div><div className="kpi-sub">This week</div></div><div className="kpi"><div className="kpi-label">Reviews due</div><div className="kpi-val">2</div><div className="kpi-sub">This month</div></div><div className="kpi kpi-red"><div className="kpi-label">Missed doses</div><div className="kpi-val">1</div><div className="kpi-sub">This week</div></div></div><div className="card"><div className="card-hd"><span className="card-title">MAR Overview — All Clients</span></div><div style={{padding:'20px',textAlign:'center',color:'var(--slate)',fontSize:'12.5px'}}>Open a client profile and go to the Medication tab to see their full MAR chart.</div></div></>);
export const BodyMapsPage   = () => (<><div className="ph"><div><div className="ph-title">Body Maps</div><div className="ph-sub">Active body map entries across all clients</div></div></div><div className="tbl-wrap"><table><thead><tr><th>Client</th><th>Location</th><th>Type</th><th>Date noted</th><th>Status</th></tr></thead><tbody>{[{client:'Mrs G Williams',loc:'Right heel',type:'Pressure sore',date:'5 Mar 2026',s:'amber'},{client:'Mrs G Williams',loc:'Left forearm',type:'Bruising',date:'10 Mar 2026',s:'green'},{client:'Mrs M Roberts',loc:'Lower back',type:'Pressure sore',date:'28 Feb 2026',s:'red'}].map((r,i)=><tr key={i}><td><span style={{fontSize:'12.5px',fontWeight:500,color:'var(--navy)'}}>{r.client}</span></td><td style={{fontSize:'12.5px'}}>{r.loc}</td><td style={{fontSize:'12px',color:'var(--slate)'}}>{r.type}</td><td style={{fontFamily:'var(--fm)',fontSize:'11.5px',color:'var(--slate)'}}>{r.date}</td><td><span className={`tag t-${r.s}`}>{r.s==='green'?'Healing':r.s==='amber'?'Monitor':'Deteriorating'}</span></td></tr>)}</tbody></table></div></>);
export const MCAPage        = () => (<><div className="ph"><div><div className="ph-title">Mental Capacity</div><div className="ph-sub">MCA assessments, LPA records and DNACPR</div></div></div><div className="kpi-row" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="kpi"><div className="kpi-label">Active MCAs</div><div className="kpi-val">4</div><div className="kpi-sub">All clients</div></div><div className="kpi kpi-amber"><div className="kpi-label">Reviews due</div><div className="kpi-val">1</div><div className="kpi-sub">This month</div></div><div className="kpi"><div className="kpi-label">LPA on file</div><div className="kpi-val">3</div><div className="kpi-sub">Registered</div></div></div><div className="card"><div className="card-hd"><span className="card-title">MCA Records</span><button className="btn btn-p btn-sm">+ Add assessment</button></div><div style={{padding:'20px',textAlign:'center',color:'var(--slate)',fontSize:'12.5px'}}>Open a client profile and go to the Mental Capacity tab to manage individual assessments.</div></div></>);
